[dev] scripts

diff --git a/run b/run
--- a/run
+++ b/run
@@ -4,7 +4,7 @@ set -eou pipefail
 pod_layer_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 function error {
-	echo -e "[error] $(date '+%F %T') - ${BASH_SOURCE[0]}:${BASH_LINENO[0]}: ${command}: ${*}" >&2
+	echo -e "[error] $(date '+%F %T') - ${BASH_SOURCE[0]}:${BASH_LINENO[0]}: ${*}" >&2
 	exit 2
 }
 
